### ISSUE TITLE
Can't log out

### ISSUE THREAD

**Issue by raddick** [sciserver/graywulf#32]
On the test SkyQuery (http://test.voservices.net/skyquery/), I was able to log in through the portal with no problem. But then I can't log out. Clicking on the "sign out" button in the top right does nothing.

**Comment by dobos** [comment]
This is likely because the you clicked on the sign out button from a page that had the token in the URL. In this case you get redirected to the login portal but then the login portal redirects you back to the very same url, with the token remaining in the query string. Either SkyQuery or the login portal should remove the token.

If you sign out from a page other than where you are redirected when signing in for the first time, sign out works as expected.

I'll revisit this issue later.

**Comment by dobos** [comment]
Fixed, now all tokens are removed from return that's sent to login portal.
